# docker-compose
version: '2.20.3'
services:
  postgres:
    image: postgres:14
    container_name: nest-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data


  backend:
    container_name: backend
    build: ./gerdastan_back
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres

  frontend:
    container_name: front
    build: ./gerdastan_front_web
    ports:
      - 80:80
    depends_on:
      - backend
    environment:
      - VITE_SERVER_URL=backend
volumes:
  postgres:
    name: nest-db
