# docker-compose
version: '3.8'
services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gdast
      - POSTGRES_PORT=5432
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  backend:
    build: ./gerdastan_back
    expose:
      - 3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env
    command: bash -c "npm run start:prod"

  frontend:
    build: ./gerdastan_front_web
    ports:
      - 80:80
    depends_on:
      - backend
    environment:
      - VITE_SERVER_URL=backend
volumes:
  postgres:
    name: nest-db
