version: '3.8'
services:
  frontend:
    container_name: front
    build: ./gerdastan_front_web
    ports:
      - 80:80
    depends_on:
      - backend
    environment:
      - VITE_SERVER_URL:backend

  backend:
    container_name: nest-api
    build: ./gerdastan_back
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:14
    container_name: nest-db
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nest-db
